using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Trust.Dal;
using Trust.Bll;

namespace Trust
{
    /// <summary>
    /// Interaction logic for TableAlais.xaml
    /// </summary>
    public partial class TableAlais : Page
    {
        public List<AlaisField> FieldList { get; set; }

        public TableAlais()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Change the displaying alais table based on the users selected
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void comboBox1_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            //get the name of the table the user wants to edit
            ComboBoxItem item = (ComboBoxItem)this.comboBox1.SelectedItem;
            string tableName = item.Name;
            Bll.Alais a = new Bll.Alais(tableName);
            this.FieldList = a.Fields;
            this.dgAlais.ItemsSource = this.FieldList;
        }

        /// <summary>
        /// Change the datagrid column details to match what we want
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgAlais_AutoGeneratedColumns(object sender, EventArgs e)
        {
            //set the details of the grid
            this.dgAlais.Columns[0].Header = "Database Field Name";
            this.dgAlais.Columns[0].IsReadOnly = true;
            this.dgAlais.Columns[1].Header = "Display Name";
            this.dgAlais.Columns[1].Width = 200;
        }

        /// <summary>
        /// Save any changes to the alaises.  
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void SaveAlaises_Click(object sender, RoutedEventArgs e)
        {
            //get the table that is being updated
            ComboBoxItem cbi = (ComboBoxItem)this.comboBox1.SelectedItem;
            string tableName = cbi.Name;

            //loop through and find the correct details
            foreach (var item in this.dgAlais.Items)
            {
                //Update the field alaises as required.  
                Bll.Alais.UpdateFieldAlais((AlaisField)item, tableName);
            }
        }
    }
}
